//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 05:40:53 AM EDT 
//


package ihe.iti.rmd._2017;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ihe.iti.rmd._2017 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RemoveDocumentsRequest_QNAME = new QName("urn:ihe:iti:rmd:2017", "RemoveDocumentsRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ihe.iti.rmd._2017
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RemoveDocumentsRequestType }
     * 
     */
    public RemoveDocumentsRequestType createRemoveDocumentsRequestType() {
        return new RemoveDocumentsRequestType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDocumentsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ihe:iti:rmd:2017", name = "RemoveDocumentsRequest")
    public JAXBElement<RemoveDocumentsRequestType> createRemoveDocumentsRequest(RemoveDocumentsRequestType value) {
        return new JAXBElement<RemoveDocumentsRequestType>(_RemoveDocumentsRequest_QNAME, RemoveDocumentsRequestType.class, null, value);
    }

}
