//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 05:40:53 AM EDT 
//


package ihe.iti.rmd._2017;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ihe.iti.xds_b._2007.DocumentRequest;


/**
 * <p>Java class for RemoveDocumentsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RemoveDocumentsRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:ihe:iti:xds-b:2007}DocumentRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RemoveDocumentsRequestType", propOrder = {
    "documentRequest"
})
public class RemoveDocumentsRequestType {

    @XmlElement(name = "DocumentRequest", namespace = "urn:ihe:iti:xds-b:2007", required = true)
    protected DocumentRequest documentRequest;

    /**
     * Gets the value of the documentRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentRequest }
     *     
     */
    public DocumentRequest getDocumentRequest() {
        return documentRequest;
    }

    /**
     * Sets the value of the documentRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentRequest }
     *     
     */
    public void setDocumentRequest(DocumentRequest value) {
        this.documentRequest = value;
    }

}
