package gov.nist.asbestos.testEngine.engine;

import com.google.common.base.Strings;
import gov.nist.asbestos.client.events.UIEvent;
import gov.nist.asbestos.client.resolver.Ref;
import gov.nist.asbestos.client.resolver.ResourceWrapper;
import gov.nist.asbestos.http.headers.Headers;
import gov.nist.asbestos.http.operations.HttpBase;
import gov.nist.asbestos.serviceproperties.ServiceProperties;
import gov.nist.asbestos.serviceproperties.ServicePropertiesEnum;
import gov.nist.asbestos.testEngine.engine.fixture.FixtureComponent;
import org.hl7.fhir.r4.model.TestScript;

import java.util.Objects;

public class FixtureLabels {
    TestDef testDef;
    boolean sourceId = false;
    boolean responseId = false;
    String rawReference;
    String referenceLabel;
    String label = null;
    String tail = "";

    public enum Source { SOURCE, RESPONSE };

    FixtureLabels(TestDef testDef) {
        this.testDef = testDef;
    }

    FixtureLabels(ActionReporter actionReporter, TestScript.SetupActionOperationComponent op, String key) {
        this(actionReporter.getAssertionSource(),
                actionReporter.getAssertionSource() == null ? null : actionReporter.getAssertionSource().getId(),
                key);
        testDef = actionReporter;
    }

    FixtureLabels(TestDef testDef, FixtureComponent assertionSource, Source source) {
        this.testDef = testDef;
        if (source == Source.SOURCE) {
            sourceId = true;
            label = "source";
        } else if (source == Source.RESPONSE) {
            sourceId = false;
            label = "response";
        }
        assignAttributes(label);

        HttpBase httpBase = assertionSource.getHttpBase();  // http operation of fixtureComponent.wrapper
        ResourceWrapper wrapper1 = assertionSource.getResourceWrapper();
        String refStrRaw = null;

        if (httpBase != null) {  // fixtureComponent created by operation
            refStrRaw = operationReport(this, httpBase, refStrRaw);
        } else if (wrapper1 != null) {   // static fixtureComponent
            refStrRaw = staticFixtureReport(this, assertionSource, wrapper1, refStrRaw);
        }
    }

    private String operationReport(FixtureLabels labels, HttpBase httpBase, String refStrRaw) {
        Headers responseHeaders = httpBase.getResponseHeaders();
        String eventUrl = responseHeaders.getProxyEvent();
        if (eventUrl != null) {
            refStrRaw = EventLinkToUILink.get(eventUrl, labels.tail);
            labels.referenceLabel = (labels.label == null) ? refStrRaw : "Open in Inspector";
            labels.rawReference = refStrRaw;
        }
        return refStrRaw;
    }

    private String staticFixtureReport(FixtureLabels labels, FixtureComponent fixtureComponent, ResourceWrapper wrapper1, String refStrRaw) {
        Objects.requireNonNull(testDef);
        Ref ref = wrapper1.getRef();
        if (ref != null) {
            String base = ServiceProperties.getInstance().getPropertyOrStop(ServicePropertiesEnum.FHIR_TOOLKIT_UI_HOME_PAGE);
            String server = ServiceProperties.getInstance().getPropertyOrStop(ServicePropertiesEnum.FHIR_TOOLKIT_BASE);
            UIEvent uiEvent = fixtureComponent.getCreatedByUIEvent();
            if (uiEvent == null) {
                // Use Cases
                // 1. Cached server object (Patient, Binary), url (dataObject) has form
                // http://localhost:8081/asbestos/static/staticResource/MHD_DocumentRecipient_minimal/Single_Document_without_Binary/Bundle/doc1.json
                // 2. Fixture Resource from within a Bundle (PDB), url (dataObject) has form
                // http://localhost:8081/asbestos/engine/staticResource/MHD_DocumentRecipient_minimal/Single_Document_without_Binary/DocumentReference?dataObject%3DBundle%2Fpdb.xml%3BfhirPath%3DBundle.entry%5B0%5D
                // This has dataObject param to guide extraction from Bundle so the generated url
                // (inspectUrl) has two nested params:
                // The inner references the server and has param to address content within Bundle
                // The outer references the UI and has inner as its reference to the content.
                // So there are two reasons for params: server reference and UI display page reference.

                // if ref contains a query, it was generated by FixtureComponent#generateStaticResourceRef
                // url points to static resource (fixture) on server
                // refStrRaw points to UI page to display it
                String url = ref.isQuery()
                        ? ref.urlEncode()
                        : new Ref(server + "/static/staticResource/"
                        + testDef.getTestCollectionId()
                        + "/" + testDef.getTestId()
                        + "/" + ref.asString()).urlEncode();
                refStrRaw = base
                        + "/inspectUrl?dataObject=" + url;
            } else {
                refStrRaw = base + "/session/" + testDef.getTestSessionId()
                        + "/channel/" + testDef.getChannelId()
                        + "/lognav/" + uiEvent.getEventName()
                        + labels.tail;
            }
        }
        return refStrRaw;
    }


    FixtureLabels(FixtureComponent assertionSource, String opSourceId, String key) {
        if (key != null && assertionSource != null && key.equals(assertionSource.getId())) {
            sourceId = true;
            label = "sourceId (" + key + ")";
        }
        if (key != null && key.equals(opSourceId)) {
            sourceId = true;
            label = "sourceId (" + key + ")";
        }
        assignAttributes(key);
    }

    FixtureLabels(ActionReporter actionReporter, TestScript.SetupActionAssertComponent op, String key) {
        this(actionReporter.getAssertionSource(), actionReporter.getAssertionSource().getId(), key);
    }

    private void assignAttributes(String key) {
        if (sourceId)
            tail = "/req";
        else if (responseId)
            tail = "/resp";
        else if (key != null && key.equals("lastOperation")) {
            tail = "/resp";
            label = key;
        }

        if (label == null) {
            label = key;
            if (key.equals("request"))
                tail = "/req";
            if (key.equals("response"))
                tail = "/resp";
        }
    }

    String getReference() {
        String label = referenceLabel;
        if (Strings.isNullOrEmpty(label))
            label = rawReference;

        return "<a href=\"" + rawReference + "\"" + " target=\"_blank\">" +
                referenceLabel +
                "</a>";
    }

}
