//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 05:40:53 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ihe:rad:xdsi-b:2009", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ihe.rad.xdsi_b._2009;
